In [ ]:
import os
os.chdir("..")
from src.pos_tagging.pos_tagging_df import pos_tagging_df
import pandas as pd
#%pip install spacy
#!python -m spacy download es_core_news_md

df = pd.read_csv('data/processed/resenas_clean.csv', sep=';')
df = df[['business_name', 'review_rating', 'review_text']]
df.sample(2)

,business_name,review_rating,review_text
1003,Ruinas de la Parroquia de Santiago Apóstol,5,"Lugar hermoso, y especial para tomar fotos"
403,Volcán Arenal,5,Espectacular

In [2]:
todos_los_registros = []

for lugar, grupo in df.groupby("business_name"):
    textos = grupo["review_text"].tolist()
    resultados_lugar = pos_tagging_df(lugar, textos)
    todos_los_registros.extend(resultados_lugar)

df_resultados = pd.DataFrame(todos_los_registros)
df_resultados =  df_resultados[df_resultados['categoria'] != 'MISC']

In [20]:
print(len(df_resultados))
df_resultados.sample(3, random_state=777)

5590

                               lugar tipo categoria   elemento  frecuencia
3402  Parque Nacional Manuel Antonio  POS       ADJ      mejor          13
5032                   Volcán Arenal  POS      NOUN     precio           5
5144                   Volcán Arenal  POS      NOUN  visitante           2